version: '2'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    image: feathers/gateway
    ports:
      - 3030:3030
    networks:
      - feathers
  service1:
    build: ./service
    container_name: service1
    image: feathers/service1
    ports:
      - 3031:3031
    networks:
      - feathers
  service2:
    build: ./service
    container_name: service2
    image: feathers/service2
    ports:
      - 3032:3032
    networks:
      - feathers

networks:
  feathers:
